#!/usr/bin/env bash
#
# Convert xml file with xsl stylesheet to pdf document

#modify this if needed 
declare -r XCONF='/usr/share/fop/conf/rosfop.xconf'
declare -r SAXON='/opt/saxon/saxon9he.jar'
declare -r PDF_READER='xdg-open' #opens the default PDF program
declare -r REFRESH=5 #refresh rate for the PDF

#don't modify unless you know what you're doing
###############################################
# Arguments: *.xml *.xsl Optional *.pdf
# Returns: none
##############################################
declare -r USAGE='Usage: convertxmltopdf myreport.xml myreportstyle.xsl [/path/to/report.pdf]'
declare -r WHATIS='Creates a PDF file from a XML and XSL (stylesheet) file.
 By default it uses the same name for the PDF file'  

converter(){
  local -i ret_value=0
  local xmlname="$1"
  local xslname="$2"
  local report_fo=$(mktemp) #use a temp file
  java -jar $SAXON -s:$xmlname -xsl:$xslname -o:$report_fo -xi 
  if [[ "$?" -eq 0 ]]; then
    local pdfname=$(_getPdfname $xmlname $3)
    fop -c $XCONF $report_fo $pdfname >&2
    rm -f "$report_fo"
    $PDF_READER "$pdfname"
  else
    ret_value+=1 
  fi
  return $ret_value
}

_getPdfname(){
  local pdfname=$1
  if [ $# -eq 2 ];then
    pdfname=$2
  fi
  pdfname=$(echo "$pdfname" | cut -d'.' -f1)
  echo "$pdfname"".pdf" 
  return 0 
}

main(){
  local -i state=0 
  if [ $# = 1 ] && [ $1 = '-h' ]; then
    echo "$WHATIS"
    state+=1
  elif [[ $1 != *.xml || $2 != *.xsl || $# -gt 3 ]]; then 
    echo "$USAGE"
    state+=1
  else
    while [[ $state -eq 0 ]]; do
      state=$(converter "$@")
      echo "error found"
      echo $noError
      sleep $REFRESH
    done
  fi
}

main "$@"
